### ISSUE TITLE
galera-status  error  at line 257

### ISSUE THREAD

**Issue by hope1234567hope** [scheidtp/galera-status#3]
run  ./galera-status  --hosts=192.168.137.216,192.168.137.244,192.168.137.247 -umonitor -p123456 --follow   
find error：
./galera-status: line 257: [[: .6250: syntax error: operand expected (error token is ".6250")en is ".132080")

my  mariadb  is 10.3.11, os is centos 7
why?

**Comment by kcgthb** [comment]
@hope1234567hope could you see if #4 fixes your issue?
